"""
Django settings for sms_prj project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pmiuhd%w18w&v)afvipml*6c36^1$d=c7@shhv_fzdp^416(9#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'accounts',
    'academics',
    'schools',
    'results',
    'attendance',
    'communications',
    'reports',
    'fees',
    'audit',
    # 'results',
    'staffs',
    'students',
    'subscriptions',
    'timetable',
    'rest_framework',
    'rest_framework_simplejwt',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sms_prj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sms_prj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

JAZZMIN_SETTINGS = {
    # --------------------
    # GENERAL
    # --------------------
    "site_title": "School Management System",
    "site_header": "School Management System",
    "site_brand": "EduManage",
    "site_logo": "images/logo.png",  # static file
    "login_logo": "images/logo.png",
    "login_logo_dark": "images/logo_dark.png",
    "site_logo_classes": "img-circle",
    "site_icon": "images/favicon.ico",

    "welcome_sign": "Welcome to EduManage Admin Panel",
    "copyright": "EduManage",

    # --------------------
    # USER INTERFACE
    # --------------------
    "search_model": ["students.Student", "staff.Teacher", "accounts.User"],
    "user_avatar": None,

    # --------------------
    # TOP MENU
    # --------------------
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Schools", "model": "schools.School"},
        {"name": "Students", "model": "students.Student"},
        {"name": "Teachers", "model": "staff.Teacher"},
        {"name": "Payments", "model": "fees.Payment"},
    ],

    # --------------------
    # USER MENU
    # --------------------
    "usermenu_links": [
        {"name": "Support", "url": "https://wa.me/234XXXXXXXXXX", "new_window": True},
        {"name": "Logout", "url": "admin:logout"},
    ],

    # --------------------
    # SIDE MENU
    # --------------------
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # --------------------
    # APP & MODEL ORDERING
    # --------------------
    "order_with_respect_to": [
        "accounts",
        "schools",
        "staff",
        "students",
        "academics",
        "attendance",
        "results",
        "fees",
        "communications",
        "timetable",
        "reports",
        "subscriptions",
        "audit",
    ],

    # --------------------
    # CUSTOM ICONS
    # --------------------
    "icons": {
        "accounts.User": "fas fa-user-shield",
        "schools.School": "fas fa-school",
        "schools.AcademicSession": "fas fa-calendar",
        "schools.Term": "fas fa-calendar-alt",

        "staff.Teacher": "fas fa-chalkboard-teacher",

        "students.Student": "fas fa-user-graduate",

        "academics.Class": "fas fa-layer-group",
        "academics.Subject": "fas fa-book",

        "attendance.Attendance": "fas fa-calendar-check",

        "results.Result": "fas fa-chart-line",

        "fees.Invoice": "fas fa-file-invoice",
        "fees.Payment": "fas fa-credit-card",

        "communications.Announcement": "fas fa-bullhorn",

        "timetable.Timetable": "fas fa-clock",

        "subscriptions.Subscription": "fas fa-crown",

        "audit.ActivityLog": "fas fa-shield-alt",
    },

    # --------------------
    # UI TWEAKS
    # --------------------
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,

    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    # --------------------
    # ADMIN LIST SETTINGS
    # --------------------
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "students.Student": "collapsible",
        "schools.School": "tabs",
    },

    # --------------------
    # LANGUAGE & TIME
    # --------------------
    "language_chooser": False,
}


JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",  # professional & clean
    "dark_mode_theme": "darkly",

    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,

    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",

    "navbar": "navbar-primary navbar-dark",
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,

    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,

    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,

    "sidebar_nav_flat_style": False,
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}
