# Generated by Django 6.0 on 2026-02-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectassignment',
            name='arm',
        ),
    ]
